name: di_example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod_annotation: ^2.3.5
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.3.10
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
