name: di_example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  injectable: ^2.4.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  build_runner:
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
